language: node_js
node_js:
  - "11"
install:
  - yarn
before_script:
  - yarn run build-css
script:
  - travis_wait yarn test
before_deploy:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local-dir: ./build
  on:
    branch: master